
package br.com.caelum.livraria.clientews;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LivrariaWS", targetNamespace = "http://webservice.livraria.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LivrariaWS {


    /**
     * 
     * @param titulo
     * @return
     *     returns java.util.List<br.com.caelum.livraria.clientews.Livro>
     */
    @WebMethod
    @WebResult(name = "autores", targetNamespace = "")
    @RequestWrapper(localName = "getLivrosPeloNome", targetNamespace = "http://webservice.livraria.caelum.com.br/", className = "br.com.caelum.livraria.clientews.GetLivrosPeloNome")
    @ResponseWrapper(localName = "getLivrosPeloNomeResponse", targetNamespace = "http://webservice.livraria.caelum.com.br/", className = "br.com.caelum.livraria.clientews.GetLivrosPeloNomeResponse")
    public List<Livro> getLivrosPeloNome(
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo);

}
