
package br.com.caelum.livraria.clientews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivrariaWSService", targetNamespace = "http://webservice.livraria.caelum.com.br/", wsdlLocation = "http://localhost:8080/livraria/LivrariaWS?wsdl")
public class LivrariaWSService
    extends Service
{

    private final static URL LIVRARIAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIVRARIAWSSERVICE_EXCEPTION;
    private final static QName LIVRARIAWSSERVICE_QNAME = new QName("http://webservice.livraria.caelum.com.br/", "LivrariaWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/livraria/LivrariaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVRARIAWSSERVICE_WSDL_LOCATION = url;
        LIVRARIAWSSERVICE_EXCEPTION = e;
    }

    public LivrariaWSService() {
        super(__getWsdlLocation(), LIVRARIAWSSERVICE_QNAME);
    }

    public LivrariaWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVRARIAWSSERVICE_QNAME, features);
    }

    public LivrariaWSService(URL wsdlLocation) {
        super(wsdlLocation, LIVRARIAWSSERVICE_QNAME);
    }

    public LivrariaWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVRARIAWSSERVICE_QNAME, features);
    }

    public LivrariaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivrariaWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LivrariaWS
     */
    @WebEndpoint(name = "LivrariaWSPort")
    public LivrariaWS getLivrariaWSPort() {
        return super.getPort(new QName("http://webservice.livraria.caelum.com.br/", "LivrariaWSPort"), LivrariaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LivrariaWS
     */
    @WebEndpoint(name = "LivrariaWSPort")
    public LivrariaWS getLivrariaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.livraria.caelum.com.br/", "LivrariaWSPort"), LivrariaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVRARIAWSSERVICE_EXCEPTION!= null) {
            throw LIVRARIAWSSERVICE_EXCEPTION;
        }
        return LIVRARIAWSSERVICE_WSDL_LOCATION;
    }

}
